0:
  county : ["基隆市", "新北市/基隆新北"]
  resevior : ["新山水庫"]
  four_region : 0 #["北部"]

1:
  county : ["臺北市", "新北市/台北新北"]
  resevior : ["翡翠水庫"]
  four_region : 0 #["北部"]

2:
  county : ["新北市/板新"]
  resevior : ["翡翠水庫", "石門水庫"]
  four_region : 0 #["北部"]

3:
  county : ["桃園市", "新北市/林口"]
  resevior : ["石門水庫"]
  four_region : 0 #["北部"]

4:
  county : ["新竹市", "新竹縣"]
  resevior : ["寶山水庫", "寶山第二水庫"]
  four_region : 0 #["北部"]

5:
  county : ["苗栗縣"]
  resevior : ["永和山水庫", "明德水庫"]
  four_region : 0 #["北部"]

6:
  county : ["臺中市"]
  resevior : ["鯉魚潭水庫", "德基水庫", "石岡壩"]
  four_region : 1 #["中部"]

7:
  county : ["彰化縣"]
  resevior : ["石岡壩", "湖山水庫", "集集攔河堰", "日月潭水庫"]
  four_region : 1 #["中部"]

8:
  county : ["南投縣"]
  resevior : ["集集攔河堰", "日月潭水庫"]
  four_region : 1 #["中部"]

9:
  county : ["雲林縣"]
  resevior : ["湖山水庫", "集集攔河堰", "日月潭水庫"]
  four_region : 1 #["中部"]

10:
  county : ["嘉義市","嘉義縣"]
  resevior : ["仁義潭水庫", "蘭潭水庫", "曾文水庫", "烏山頭水庫"] # 87%[仁義潭&蘭潭平均] & 13%[曾文&烏山頭平均]
  four_region : 1 #["中部"]

11:
  county : ["臺南市"]
  resevior : ["南化水庫", "曾文水庫", "烏山頭水庫"] # 60%[南化] 40%[曾文&烏山頭平均]
  four_region : 2 #["南部"]

12:
  county : ["高雄市"]
  resevior : ["阿公店水庫", "澄清湖水庫", "鳳山水庫"] 
  four_region : 2 #["南部"]

13:
  county : ["屏東縣"]
  resevior : ["牡丹水庫"]
  four_region : 2 #["南部"]